"""Alle teksten en vaste gegevens van casperboekee.com op één plek.

Prijzen, contactgegevens en het formulier pas je hier aan; daarna `python3 build.py` draaien.
"""

SITE = {
    "base_url": "https://www.casperboekee.com/",
    "name": "Casper Boekee Personal Training",
    "person": "Casper Boekee",
    "email": "info@casperboekee.com",
    "phone_display": "+31 6 1552 4981",
    "phone_tel": "+31615524981",
    "whatsapp": "https://wa.me/31615524981",
    "instagram": "https://www.instagram.com/casperboekee/",
    "gym": "Patrick's Gym",
    "street": "Marius Bauerstraat 28",
    "postcode": "1062 AR",
    "city": "Amsterdam",
    "kvk": "89761286",
    "maps": "https://www.google.com/maps/search/?api=1&query=Patrick%27s+Gym+Marius+Bauerstraat+28+1062+AR+Amsterdam&query_place_id=ChIJsXZQkj3ixUcRW4WKGx14nj0",
    "year": "2026",
    # Contactformulier (Web3Forms). Leeg = formulier staat in testmodus en verstuurt niets.
    "form_key": "a7fcf73f-2766-4a95-b37b-6831a1db2fb0",
    "form_endpoint": "https://api.web3forms.com/submit",
    # Bestaande koppelingen met Google Search Console en Bing, overgenomen van de Wix-site.
    "google_verification": "QxGgNyW0cyuzLlevlwItlIXFiYEFLnjOev5lOdkM6eo",
    "bing_verification": "2EDCC83D59D72E75CD29E96C48892E0F",
    # Prijzen (één plek)
    "price_single": "€85",
    "price_ten": "€850",
    "price_scan": "€250",
    # Later: link naar de klantomgeving van het PT-systeem. Leeg = knop wordt niet getoond.
    "client_portal_url": "",
    # GoatCounter (cookievrije bezoekersteller): alleen de accountnaam, bv. "casperboekee". Leeg = uit.
    "goatcounter": "casperboekee",
    # Reviews en clips: leeg = blok wordt niet getoond.
    "reviews": [],
    "clips": [{"src": "assets/video/padwork.mp4", "poster": "assets/img/padwork-poster.jpg", "w": 720, "h": 1280}],
}

EN = {
    "lang": "en",
    "html_lang": "en",
    "other_label": "Nederlands",
    "skip": "Skip to content",
    "menu": "Menu",
    "close": "Close",
    "nav": {
        "personal-training": "Personal Training",
        "muay-thai": "Muay Thai",
        "performance-scan": "Performance Scan",
        "prices": "Prices",
        "contact": "Contact",
    },
    "cta_short": "Free intro",
    "cta": "Book your free intro",
    "cta_wa": "WhatsApp me",
    "cta_note": "Free · 30 minutes · at Patrick's Gym",
    "logo_sub": ["Personal", "Trainer"],
    "whatsapp_text": "Hi Casper, I'm interested in personal training",
    "more": "More",
    "chips": ["Certified · Fitvak A&B", "100% 1-on-1", "Patrick's Gym Amsterdam"],
    "meta": {
        "home": {
            "title": "Personal Trainer Amsterdam | Muay Thai | Casper Boekee",
            "desc": "1-on-1 personal training in Amsterdam: Muay Thai, strength & conditioning and functional training. Certified trainer at Patrick's Gym. Book a free 30-minute intro.",
        },
        "personal-training": {
            "title": "Personal Training Amsterdam | Functional Strength | Casper Boekee",
            "desc": "1-on-1 personal training in Amsterdam. Get stronger, fitter and move with less pain with a clear plan and measurable progress. Free 30-minute intro at Patrick's Gym.",
        },
        "muay-thai": {
            "title": "Muay Thai Training Amsterdam | 1-on-1 | Casper Boekee",
            "desc": "1-on-1 Muay Thai training in Amsterdam: technique, padwork and conditioning, from complete beginner to experienced fighter. Free 30-minute intro at Patrick's Gym.",
        },
        "performance-scan": {
            "title": "Performance Scan Amsterdam | Casper Boekee",
            "desc": "90-minute performance assessment in Amsterdam with 20+ measurements: heart rate, blood pressure, body composition, posture, mobility, strength and conditioning. Personal report and action plan. €250.",
        },
        "contact": {
            "title": "Contact & Free Intro | Casper Boekee",
            "desc": "Request a free 30-minute intro with personal trainer Casper Boekee at Patrick's Gym, Amsterdam. Use the form, WhatsApp or email.",
        },
        "privacy": {
            "title": "Privacy | Casper Boekee",
            "desc": "How Casper Boekee Personal Training handles the details you send through the contact form.",
        },
    },
    "home": {
        "eyebrow": "Personal trainer · Amsterdam",
        "lockup": ["Muay Thai", "& Functional Strength", "Personal Training"],
        "lead": "1-on-1 personal training in Amsterdam. Get stronger, fitter and move with less pain, with a clear plan and measurable progress.",
        "hero_alt": "Casper Boekee holding Thai pads for a client in the ring at Patrick's Gym",
        "services_eyebrow": "Training",
        "services_h": "Two ways to train. One clear plan.",
        "band": "Whether you want to learn Muay Thai, build muscle, lose weight or get stronger: together we'll work towards your goal.",
        "band_alt": "Clinch work during a Muay Thai session",
        "gallery_eyebrow": "In the ring",
        "gallery_h": "Training at Patrick's Gym",
        "reviews_eyebrow": "Reviews",
        "reviews_h": "What clients say",
    },
    "services": {
        "pt": {
            "title": "Personal Training",
            "sub": "Functional strength",
            "text": "Increase your strength, balance and endurance with functional strength training, built around your goal.",
            "meta": "60 min · 1-on-1",
            "link": "More about personal training",
            "alt": "Portrait of Casper Boekee holding Thai pads",
        },
        "mt": {
            "title": "Muay Thai",
            "sub": "Technique & padwork",
            "text": "Learn traditional, authentic Muay Thai and refine your technique. From your first jab to fight conditioning.",
            "meta": "60 min · 1-on-1",
            "link": "More about Muay Thai",
            "alt": "Kick drill on the pads during a Muay Thai session",
        },
        "scan": {
            "title": "Performance Scan",
            "text": "20+ measurements of your heart rate, blood pressure, body composition, posture, mobility, strength and conditioning. With a personal report and action plan.",
            "meta": "90 min · €250",
            "link": "More about the scan",
        },
    },
    "how": {
        "eyebrow": "How it works",
        "h": "From first meeting to measurable progress",
        "steps": [
            ("Free intro", "We meet at Patrick's Gym for 30 minutes and talk about your goals, your background and what has or hasn't worked before."),
            ("Assessment", "I measure your starting point: strength, mobility, conditioning and posture."),
            ("Your plan", "You get a clear training plan built around your goal, schedule and body."),
            ("Train & track", "We train 1-on-1 and re-test regularly, so you see your progress in numbers."),
        ],
    },
    "prices": {
        "eyebrow": "Prices",
        "h": "Clear prices",
        "single": {"qty": "1", "unit": ["PT", "session"], "meta": "60 minutes · 1-on-1 · Muay Thai or functional strength"},
        "ten": {
            "qty": "10", "unit": ["PT", "sessions"], "tag": "Best value",
            "meta": "60 minutes per session · 1-on-1 · including:",
            "plus": ["Premium performance assessment at the start", "Personal training plan built around your goal", "Re-tests along the way, so you see your progress in numbers"],
        },
        "scan": "Performance Scan · 90 min · €250. Fully deducted when you start a 10-session package or coaching programme within 14 days.",
        "pay": "You'll receive an invoice by email. Pay with iDEAL or bank transfer.",
        "start": "Not sure yet? Start with a free 30-minute intro.",
    },
    "about": {
        "eyebrow": "About me",
        "h": "I'm Casper.",
        "p": [
            "I'm a certified personal trainer and fitness instructor from Amsterdam (Fitvak A&B, and currently completing the NASM CPT). I combine Muay Thai, strength & conditioning and functional performance training to help you build real power, endurance and conditioning.",
            "My goal is for you to become stronger, fitter, more confident and more disciplined, physically and mentally. I coach complete beginners as well as experienced fighters, and everyone gets a plan with progress you can measure.",
            "You'll find me at Patrick's Gym in Amsterdam, where I've been coaching personal training, strength & conditioning and Muay Thai for over two years.",
        ],
        "alt": "Casper Boekee with Thai pads and belly pad",
        "chips": ["2+ years at Patrick's Gym", "Beginners to fighters", "NASM CPT in progress"],
    },
    "gallery_alts": {
        "g-elbowside": "Elbow strike on the pads, seen from the side",
        "g-gloveclose": "Close-up of a glove landing on a Thai pad",
        "g-intense": "Casper Boekee looking through raised Thai pads",
        "g-elbowcorner": "Elbow drill in the corner of the ring",
        "g-clinch": "Clinch drill in the ring",
    },
    "faq": {
        "eyebrow": "FAQ",
        "h": "Frequently asked questions",
        "items": {
            "results": ("What results can I expect?", "You get stronger, fitter and move with less pain, with progress you can measure. We test at the start and re-test regularly, so you see it in numbers."),
            "one": ("Is the training 1-on-1?", "Yes. Every session is 1-on-1, tailored to your goal and level."),
            "coaching": ("What does the coaching look like?", "You get a clear plan instead of random workouts. We start with an intro and an assessment, then train 1-on-1 and re-test regularly, so your progress stays visible."),
            "mt": ("Do you offer Muay Thai sessions?", "Yes. You can book Muay Thai on its own or combine it with strength training, depending on your goal."),
            "mt_expect": ("What can I expect from a Muay Thai session?", "Technique, padwork and conditioning, built up step by step. You learn to punch, kick, knee and elbow properly, and you get fitter while doing it."),
            "beginners": ("Is Muay Thai suitable for beginners?", "Absolutely. I coach complete beginners to experienced fighters, step by step."),
            "where": ("Where do the sessions take place?", "At Patrick's Gym, Marius Bauerstraat 28, 1062 AR Amsterdam."),
            "book": ("How do I book a session?", "Request a free intro through the form or send a WhatsApp. I'll reply personally within 24 hours."),
            "pay": ("How do I pay?", "You'll receive an invoice by email. Pay with iDEAL or bank transfer."),
        },
    },
    "contact": {
        "eyebrow": "Free intro",
        "h": "Let's meet.",
        "lead": "Request a free 30-minute intro at Patrick's Gym. We talk about your goal and see if we're a match. No strings attached.",
        "points": ["Free, 30 minutes", "At Patrick's Gym, Amsterdam", "Personal reply within 24 hours"],
        "direct": "Prefer to get in touch directly?",
        "alt": "Casper Boekee with Thai pads",
        "form": {
            "name": "Name",
            "email": "Email",
            "phone": "Phone (optional)",
            "interest": "I'm interested in",
            "options": ["Personal training", "Muay Thai", "Both", "Performance Scan", "Not sure yet"],
            "message": "Your goal",
            "placeholder": "Tell me briefly what you want to achieve",
            "submit": "Request free intro",
            "sending": "Sending…",
            "privacy": "I only use your details to reply to your request.",
            "privacy_link": "Privacy statement",
            "success": "Thanks! Your request is in. I'll get back to you personally.",
            "error": "Something went wrong. Please send a WhatsApp or email info@casperboekee.com.",
            "demo": "Test mode: the form isn't connected yet, so nothing was sent.",
            "subject": "New intro request via casperboekee.com",
        },
        "labels": {"whatsapp": "WhatsApp", "email": "Email", "phone": "Phone", "location": "Location", "route": "Open in Google Maps", "instagram": "Instagram"},
    },
    "footer": {
        "kvk": "Chamber of Commerce",
        "rights": "All rights reserved.",
        "privacy": "Privacy",
        "portal": "Client login",
    },
    "cta_band": {"h": "Book your free intro today", "p": "30 minutes at Patrick's Gym. We talk about your goal and see if we're a match."},
    "pt": {
        "eyebrow": "Personal training · Amsterdam",
        "h1": "Personal Training",
        "sub": "Functional Strength",
        "lead": "Stronger, fitter and moving with less pain. You train 1-on-1 with a plan built around your goal, your schedule and your body.",
        "hero_alt": "Casper Boekee coaching a client on the pads at Patrick's Gym",
        "feat_eyebrow": "What we work on",
        "feat_h": "Strength you can use.",
        "features": [
            ("Strength", "Build muscle and get stronger with free weights and gym equipment, at a level that fits you."),
            ("Movement", "Better mobility, posture and balance, so you move more easily and with less pain."),
            ("Conditioning", "More endurance and energy, in the gym and in daily life."),
            ("Body composition", "Lose weight or build muscle with a plan you can stick to."),
        ],
        "who_eyebrow": "Who it's for",
        "who_h": "For every level",
        "who": [
            "You're new to the gym and want to start the right way.",
            "You've trained before but miss structure and progress.",
            "You want to move with less pain and feel stronger in daily life.",
            "You're a runner or recreational athlete and want to perform better.",
            "You want to stay strong and fit as you get older.",
        ],
        "session_eyebrow": "In the gym",
        "session_h": "What a session looks like",
        "session_p": "Every session takes 60 minutes and is fully 1-on-1 at Patrick's Gym. We follow your plan, I coach your technique on every exercise and we keep track of your progress, so each session builds on the last.",
        "mid_alt": "Casper Boekee holding pads during a 1-on-1 session",
        "faq": ["results", "one", "coaching", "where", "book", "pay"],
    },
    "mt": {
        "eyebrow": "Muay Thai · Amsterdam",
        "h1": "Muay Thai",
        "sub": "Technique, Padwork & Conditioning",
        "lead": "Learn traditional, authentic Muay Thai and refine your technique in 1-on-1 sessions. From complete beginner to experienced fighter.",
        "hero_alt": "Kick drill on the Thai pads in the ring",
        "feat_eyebrow": "The training",
        "feat_h": "What you train",
        "features": [
            ("Technique", "Stance, footwork, punches, kicks, knees, elbows and clinch. Step by step, with attention to detail."),
            ("Padwork", "Rounds on the pads with direct feedback, so technique becomes timing and power."),
            ("Conditioning", "Fight conditioning that makes you fitter and sharper, whether you compete or not."),
            ("Strength for fighters", "Strength & conditioning that supports your Muay Thai: more power, better balance, fewer weak spots."),
        ],
        "who_eyebrow": "Who it's for",
        "who_h": "For every level",
        "levels": [
            ("Beginner", "Never trained before? We start with the basics and build from there."),
            ("Getting fit", "Want to get fit with a sport that stays interesting? Muay Thai trains your whole body."),
            ("Fighter", "Already training or competing? We sharpen your technique and work on your weak points."),
        ],
        "combine": "You can book Muay Thai on its own or combine it with strength training, depending on your goal.",
        "clips_eyebrow": "Clips",
        "clips_h": "Padwork in the ring",
        "clips_p": "Sharp technique, real power and feedback on every round. This is what a 1-on-1 Muay Thai session with me looks like at Patrick's Gym.",
        "clips_placeholder": "Your padwork video goes here.",
        "faq": ["mt", "mt_expect", "beginners", "where", "book"],
    },
    "scan": {
        "eyebrow": "Performance Scan · Amsterdam",
        "h1": "Performance Scan",
        "sub": "Your complete baseline",
        "lead": "More than 20 measurements of your health, body, movement, strength and fitness. Know exactly where you stand, and what to do next.",
        "intro": "Not a quick weigh-in, but a full 90-minute assessment. I measure your vitals, body composition, posture, mobility, strength and conditioning with professional equipment, then turn the results into a clear report and a personal action plan.",
        "facts": [("Duration", "90 min"), ("Measurements", "20+"), ("Investment", "€250")],
        "hero_alt": "Casper Boekee holding Thai pads in the ring, in black and white",
        "feat_eyebrow": "The assessment",
        "feat_h": "What we test",
        "tests": [
            ("Health & vitals", "Your starting point, before we load anything.", ["Resting heart rate", "Blood pressure", "Height and body weight"]),
            ("Body composition", "Measured with a skinfold caliper and tape, not estimated by a scale.", ["Body fat percentage (skinfold measurement)", "Circumferences: waist, hips, chest, arms and thighs", "Waist-to-hip ratio"]),
            ("Posture", "A static posture analysis of five key areas.", ["Head position", "Shoulders", "Upper back", "Pelvic position", "Alignment of legs and feet"]),
            ("Movement & mobility", "How well you move, measured in degrees with a goniometer.", ["Overhead squat assessment", "Shoulder mobility", "Hip mobility", "Hamstring flexibility", "Ankle mobility"]),
            ("Strength & stability", "Tested at your level, left and right.", ["Grip strength with a hand dynamometer", "Single-leg balance", "Core stability", "Strength tests suited to your level"]),
            ("Conditioning", "A cardio test with live heart rate monitoring (Polar H10).", ["Cardio test with heart rate zones", "Heart rate recovery", "Estimated VO2max"]),
        ],
        "get_eyebrow": "What you get",
        "get_h": "Results you can act on",
        "deliverables": [
            ("Personal report", "All your results in one clear report, compared with norms for your age and sex."),
            ("Top 3 priorities", "What matters most for your goal right now, and why."),
            ("Action plan", "Concrete training recommendations you can start with straight away."),
            ("Review call", "20 to 30 minutes to go through your report and options together."),
        ],
        "how_eyebrow": "How it works",
        "how_h": "From intake to action plan",
        "steps": [
            ("Intake form", "Fill in the intake form, so I know your goals, history and any injuries."),
            ("The scan", "75 to 90 minutes at Patrick's Gym, adjusted to your level."),
            ("Your report", "Your personal report within 48 hours: results, your top 3 priorities and an action plan."),
            ("Review call", "A 20 to 30 minute call to go through your report and options."),
        ],
        "invest_eyebrow": "Investment",
        "invest_h": "€250",
        "invest_p": "Start a 10-session package or a coaching programme within 14 days and the full €250 is deducted.",
        "cta": "Plan your scan",
        "cta_btn": "Send a message",
        "cta_p": "Send me a message through the contact form or WhatsApp to plan your scan.",
    },
    "contact_page": {
        "eyebrow": "Contact",
        "h1": "Get in touch",
        "lead": "Questions about Muay Thai, strength training or personal coaching? Send me a message and let's talk about your goal.",
    },
    "privacy": {
        "eyebrow": "Privacy",
        "h1": "Privacy statement",
        "updated": "Last updated: 30 September 2026",
        "sections": [
            ("Who I am", ["Casper Boekee Personal Training, Amsterdam. Chamber of Commerce number 89761286. For questions about your data: info@casperboekee.com."]),
            ("What I collect", ["When you send the contact form, I receive your name, email address, phone number (if you fill it in), what you're interested in and your message.", "Please don't share medical details in the form. We discuss those in person during the intake."]),
            ("Why", ["I use your details only to reply to your request and to plan your intro or session. I don't use them for newsletters or advertising."]),
            ("How long", ["I keep your request for as long as needed to handle it. If you don't become a client, I delete it within 12 months."]),
            ("Who else processes it", ["The form is delivered to my mailbox by Web3Forms. My email is hosted by Google. This website is hosted by GitHub Pages, which logs visitors' IP addresses for security, and loads its fonts from Google Fonts.", "This website doesn't use analytics or tracking cookies."]),
            ("Your rights", ["You can ask me to see, correct or delete your data at any time by emailing info@casperboekee.com. You can also file a complaint with the Dutch Data Protection Authority (Autoriteit Persoonsgegevens)."]),
        ],
    },
    "notfound": {"h1": "Page not found", "p": "This page doesn't exist (any more).", "link": "Back to home"},
}

NL = {
    "lang": "nl",
    "html_lang": "nl",
    "other_label": "English",
    "skip": "Naar de inhoud",
    "menu": "Menu",
    "close": "Sluiten",
    "nav": {
        "personal-training": "Personal Training",
        "muay-thai": "Muay Thai",
        "performance-scan": "Performance Scan",
        "prices": "Prijzen",
        "contact": "Contact",
    },
    "cta_short": "Gratis kennismaking",
    "cta": "Plan je gratis kennismaking",
    "cta_wa": "Stuur een WhatsApp",
    "cta_note": "Gratis · 30 minuten · bij Patrick's Gym",
    "logo_sub": ["Personal", "Trainer"],
    "whatsapp_text": "Hoi Casper, ik heb interesse in personal training",
    "more": "Meer",
    "chips": ["Gecertificeerd · Fitvak A&B", "100% 1-op-1", "Patrick's Gym Amsterdam"],
    "meta": {
        "home": {
            "title": "Personal Trainer Amsterdam | Muay Thai | Casper Boekee",
            "desc": "1-op-1 personal training in Amsterdam: Muay Thai, strength & conditioning en functionele training. Gecertificeerd trainer bij Patrick's Gym. Plan een gratis kennismaking van 30 minuten.",
        },
        "personal-training": {
            "title": "Personal Training Amsterdam | Functionele Kracht | Casper Boekee",
            "desc": "1-op-1 personal training in Amsterdam. Word sterker, fitter en beweeg met minder pijn, met een duidelijk plan en meetbare progressie. Gratis kennismaking bij Patrick's Gym.",
        },
        "muay-thai": {
            "title": "Muay Thai Training Amsterdam | 1-op-1 | Casper Boekee",
            "desc": "1-op-1 Muay Thai-training in Amsterdam: techniek, padwork en conditie, van complete beginner tot ervaren vechter. Gratis kennismaking van 30 minuten bij Patrick's Gym.",
        },
        "performance-scan": {
            "title": "Performance Scan Amsterdam | Casper Boekee",
            "desc": "Performance assessment van 90 minuten in Amsterdam met 20+ metingen: hartslag, bloeddruk, lichaamssamenstelling, houding, mobiliteit, kracht en conditie. Persoonlijk rapport en actieplan. €250.",
        },
        "contact": {
            "title": "Contact & gratis kennismaking | Casper Boekee",
            "desc": "Vraag een gratis kennismaking van 30 minuten aan met personal trainer Casper Boekee bij Patrick's Gym, Amsterdam. Via het formulier, WhatsApp of e-mail.",
        },
        "privacy": {
            "title": "Privacy | Casper Boekee",
            "desc": "Hoe Casper Boekee Personal Training omgaat met de gegevens die je via het contactformulier stuurt.",
        },
    },
    "home": {
        "eyebrow": "Personal trainer · Amsterdam",
        "lockup": ["Muay Thai", "& Functionele Kracht", "Personal Training"],
        "lead": "1-op-1 personal training in Amsterdam. Word sterker, fitter en beweeg met minder pijn, met een duidelijk plan en meetbare progressie.",
        "hero_alt": "Casper Boekee houdt Thai pads vast voor een klant in de ring bij Patrick's Gym",
        "services_eyebrow": "Training",
        "services_h": "Twee manieren om te trainen. Eén duidelijk plan.",
        "band": "Of je nu Muay Thai wilt leren, spieren wilt opbouwen, wilt afvallen of sterker wilt worden: samen werken we aan jouw doel.",
        "band_alt": "Clinchwerk tijdens een Muay Thai-training",
        "gallery_eyebrow": "In de ring",
        "gallery_h": "Trainen bij Patrick's Gym",
        "reviews_eyebrow": "Reviews",
        "reviews_h": "Wat klanten zeggen",
    },
    "services": {
        "pt": {
            "title": "Personal Training",
            "sub": "Functionele kracht",
            "text": "Word sterker en verbeter je balans en uithoudingsvermogen met functionele krachttraining, afgestemd op jouw doel.",
            "meta": "60 min · 1-op-1",
            "link": "Meer over personal training",
            "alt": "Portret van Casper Boekee met Thai pads",
        },
        "mt": {
            "title": "Muay Thai",
            "sub": "Techniek & padwork",
            "text": "Leer authentiek, traditioneel Muay Thai en verfijn je techniek. Van je eerste jab tot fightconditie.",
            "meta": "60 min · 1-op-1",
            "link": "Meer over Muay Thai",
            "alt": "Trap-oefening op de pads tijdens een Muay Thai-training",
        },
        "scan": {
            "title": "Performance Scan",
            "text": "20+ metingen van je hartslag, bloeddruk, lichaamssamenstelling, houding, mobiliteit, kracht en conditie. Met een persoonlijk rapport en actieplan.",
            "meta": "90 min · €250",
            "link": "Meer over de scan",
        },
    },
    "how": {
        "eyebrow": "Zo werkt het",
        "h": "Van eerste kennismaking tot meetbare progressie",
        "steps": [
            ("Gratis kennismaking", "We spreken 30 minuten af bij Patrick's Gym en bespreken je doelen, je achtergrond en wat eerder wel of niet werkte."),
            ("Assessment", "Ik meet je startpunt: kracht, mobiliteit, conditie en houding."),
            ("Jouw plan", "Je krijgt een duidelijk trainingsplan, afgestemd op je doel, je agenda en je lichaam."),
            ("Trainen & meten", "We trainen 1-op-1 en testen regelmatig opnieuw, zodat je je vooruitgang in cijfers ziet."),
        ],
    },
    "prices": {
        "eyebrow": "Prijzen",
        "h": "Duidelijke prijzen",
        "single": {"qty": "1", "unit": ["PT-", "sessie"], "meta": "60 minuten · 1-op-1 · Muay Thai of functionele kracht"},
        "ten": {
            "qty": "10", "unit": ["PT-", "sessies"], "tag": "Meeste waarde",
            "meta": "60 minuten per sessie · 1-op-1 · inclusief:",
            "plus": ["Premium performance assessment bij de start", "Persoonlijk trainingsplan, afgestemd op je doel", "Hertests onderweg, zodat je je progressie in cijfers ziet"],
        },
        "scan": "Performance Scan · 90 min · €250. Wordt volledig verrekend als je binnen 14 dagen start met een 10-sessiepakket of coachingtraject.",
        "pay": "Je ontvangt een factuur per e-mail. Betalen kan met iDEAL of bankoverschrijving.",
        "start": "Nog niet zeker? Begin met een gratis kennismaking van 30 minuten.",
    },
    "about": {
        "eyebrow": "Over mij",
        "h": "Ik ben Casper.",
        "p": [
            "Ik ben gecertificeerd personal trainer en fitnessinstructeur uit Amsterdam (Fitvak A&B, en ik rond nu de NASM CPT af). Ik combineer Muay Thai, strength & conditioning en functionele performancetraining, zodat jij echte kracht, uithoudingsvermogen en conditie opbouwt.",
            "Mijn doel is dat je sterker, fitter, zelfverzekerder en gedisciplineerder wordt, fysiek én mentaal. Ik coach complete beginners en ervaren vechters, en iedereen krijgt een plan met progressie die je kunt meten.",
            "Je vindt me bij Patrick's Gym in Amsterdam, waar ik al ruim twee jaar personal training, strength & conditioning en Muay Thai geef.",
        ],
        "alt": "Casper Boekee met Thai pads en buikpad",
        "chips": ["2+ jaar bij Patrick's Gym", "Van beginner tot vechter", "NASM CPT in opleiding"],
    },
    "gallery_alts": {
        "g-elbowside": "Elleboogstoot op de pads, van opzij gezien",
        "g-gloveclose": "Close-up van een handschoen op een Thai pad",
        "g-intense": "Casper Boekee kijkt tussen opgeheven Thai pads door",
        "g-elbowcorner": "Elleboog-oefening in de hoek van de ring",
        "g-clinch": "Clinch-oefening in de ring",
    },
    "faq": {
        "eyebrow": "FAQ",
        "h": "Veelgestelde vragen",
        "items": {
            "results": ("Welke resultaten kan ik verwachten?", "Je wordt sterker en fitter en beweegt met minder pijn, met progressie die je kunt meten. We testen bij de start en daarna regelmatig opnieuw, zodat je het in cijfers terugziet."),
            "one": ("Is de training 1-op-1?", "Ja. Elke sessie is 1-op-1 en afgestemd op jouw doel en niveau."),
            "coaching": ("Hoe ziet de coaching eruit?", "Je krijgt een duidelijk plan in plaats van losse workouts. We beginnen met een kennismaking en een assessment, trainen daarna 1-op-1 en testen regelmatig opnieuw, zodat je vooruitgang zichtbaar blijft."),
            "mt": ("Geef je ook Muay Thai-trainingen?", "Ja. Je kunt Muay Thai los boeken of combineren met krachttraining, afhankelijk van je doel."),
            "mt_expect": ("Wat kan ik verwachten van een Muay Thai-training?", "Techniek, padwork en conditie, stap voor stap opgebouwd. Je leert goed stoten, trappen, knieën en ellebogen, en je wordt er fitter van."),
            "beginners": ("Is Muay Thai geschikt voor beginners?", "Zeker. Ik coach complete beginners tot ervaren vechters, stap voor stap."),
            "where": ("Waar vinden de trainingen plaats?", "Bij Patrick's Gym, Marius Bauerstraat 28, 1062 AR Amsterdam."),
            "book": ("Hoe boek ik een training?", "Vraag een gratis kennismaking aan via het formulier of stuur een WhatsApp. Ik reageer persoonlijk binnen 24 uur."),
            "pay": ("Hoe betaal ik?", "Je ontvangt een factuur per e-mail. Betalen kan met iDEAL of bankoverschrijving."),
        },
    },
    "contact": {
        "eyebrow": "Gratis kennismaking",
        "h": "Kom kennismaken.",
        "lead": "Vraag een gratis kennismaking van 30 minuten aan bij Patrick's Gym. We bespreken je doel en kijken of het klikt. Je zit nergens aan vast.",
        "points": ["Gratis, 30 minuten", "Bij Patrick's Gym, Amsterdam", "Persoonlijk antwoord binnen 24 uur"],
        "direct": "Liever direct contact?",
        "alt": "Casper Boekee met Thai pads",
        "form": {
            "name": "Naam",
            "email": "E-mail",
            "phone": "Telefoon (optioneel)",
            "interest": "Ik heb interesse in",
            "options": ["Personal training", "Muay Thai", "Beide", "Performance Scan", "Weet ik nog niet"],
            "message": "Je doel",
            "placeholder": "Vertel kort wat je wilt bereiken",
            "submit": "Vraag gratis kennismaking aan",
            "sending": "Versturen…",
            "privacy": "Ik gebruik je gegevens alleen om op je aanvraag te reageren.",
            "privacy_link": "Privacyverklaring",
            "success": "Bedankt! Je aanvraag is binnen. Ik neem persoonlijk contact met je op.",
            "error": "Er ging iets mis. Stuur een WhatsApp of mail naar info@casperboekee.com.",
            "demo": "Testmodus: het formulier is nog niet gekoppeld, dus er is niets verstuurd.",
            "subject": "Nieuwe kennismakingsaanvraag via casperboekee.com",
        },
        "labels": {"whatsapp": "WhatsApp", "email": "E-mail", "phone": "Telefoon", "location": "Locatie", "route": "Open in Google Maps", "instagram": "Instagram"},
    },
    "footer": {
        "kvk": "KvK",
        "rights": "Alle rechten voorbehouden.",
        "privacy": "Privacy",
        "portal": "Klantomgeving",
    },
    "cta_band": {"h": "Plan vandaag je gratis kennismaking", "p": "30 minuten bij Patrick's Gym. We bespreken je doel en kijken of het klikt."},
    "pt": {
        "eyebrow": "Personal training · Amsterdam",
        "h1": "Personal Training",
        "sub": "Functionele Kracht",
        "lead": "Sterker, fitter en bewegen met minder pijn. Je traint 1-op-1 met een plan dat past bij je doel, je agenda en je lichaam.",
        "hero_alt": "Casper Boekee coacht een klant op de pads bij Patrick's Gym",
        "feat_eyebrow": "Waar we aan werken",
        "feat_h": "Kracht waar je iets aan hebt.",
        "features": [
            ("Kracht", "Bouw spiermassa op en word sterker met vrije gewichten en apparatuur, op een niveau dat bij je past."),
            ("Beweging", "Betere mobiliteit, houding en balans, zodat je makkelijker en met minder pijn beweegt."),
            ("Conditie", "Meer uithoudingsvermogen en energie, in de gym en in het dagelijks leven."),
            ("Lichaamssamenstelling", "Afvallen of spiermassa opbouwen met een plan dat je volhoudt."),
        ],
        "who_eyebrow": "Voor wie",
        "who_h": "Voor elk niveau",
        "who": [
            "Je bent nieuw in de gym en wilt meteen goed beginnen.",
            "Je traint al langer, maar mist structuur en vooruitgang.",
            "Je wilt met minder pijn bewegen en je sterker voelen in het dagelijks leven.",
            "Je bent hardloper of recreatief sporter en wilt beter presteren.",
            "Je wilt sterk en fit blijven nu je ouder wordt.",
        ],
        "session_eyebrow": "In de gym",
        "session_h": "Zo ziet een sessie eruit",
        "session_p": "Elke sessie duurt 60 minuten en is volledig 1-op-1 bij Patrick's Gym. We volgen jouw plan, ik coach je techniek bij elke oefening en we houden je progressie bij, zodat elke sessie voortbouwt op de vorige.",
        "mid_alt": "Casper Boekee houdt pads vast tijdens een 1-op-1 sessie",
        "faq": ["results", "one", "coaching", "where", "book", "pay"],
    },
    "mt": {
        "eyebrow": "Muay Thai · Amsterdam",
        "h1": "Muay Thai",
        "sub": "Techniek, Padwork & Conditie",
        "lead": "Leer authentiek, traditioneel Muay Thai en verfijn je techniek in 1-op-1 sessies. Van complete beginner tot ervaren vechter.",
        "hero_alt": "Trap-oefening op de Thai pads in de ring",
        "feat_eyebrow": "De training",
        "feat_h": "Wat je traint",
        "features": [
            ("Techniek", "Stand, voetenwerk, stoten, trappen, knieën, ellebogen en clinch. Stap voor stap, met oog voor detail."),
            ("Padwork", "Rondes op de pads met directe feedback, zodat techniek timing en kracht wordt."),
            ("Conditie", "Fightconditie waar je fitter en scherper van wordt, of je nu wedstrijden vecht of niet."),
            ("Kracht voor vechters", "Strength & conditioning die je Muay Thai ondersteunt: meer power, betere balans, minder zwakke plekken."),
        ],
        "who_eyebrow": "Voor wie",
        "who_h": "Voor elk niveau",
        "levels": [
            ("Beginner", "Nog nooit getraind? We beginnen bij de basis en bouwen van daaruit op."),
            ("Fitter worden", "Wil je fit worden met een sport die leuk blijft? Muay Thai traint je hele lichaam."),
            ("Vechter", "Train of vecht je al? We scherpen je techniek aan en werken aan je zwakke punten."),
        ],
        "combine": "Je kunt Muay Thai los boeken of combineren met krachttraining, afhankelijk van je doel.",
        "clips_eyebrow": "Clips",
        "clips_h": "Padwork in de ring",
        "clips_p": "Scherpe techniek, echte power en feedback op elke ronde. Zo ziet een 1-op-1 Muay Thai-training met mij eruit bij Patrick's Gym.",
        "clips_placeholder": "Hier komt je padwork-video.",
        "faq": ["mt", "mt_expect", "beginners", "where", "book"],
    },
    "scan": {
        "eyebrow": "Performance Scan · Amsterdam",
        "h1": "Performance Scan",
        "sub": "Je complete nulmeting",
        "lead": "Meer dan 20 metingen van je gezondheid, lichaam, beweging, kracht en conditie. Weet precies waar je staat en wat je volgende stap is.",
        "intro": "Geen snelle weegsessie, maar een volledig assessment van 90 minuten. Ik meet je vitale waarden, lichaamssamenstelling, houding, mobiliteit, kracht en conditie met professionele apparatuur, en vertaal de resultaten naar een helder rapport en een persoonlijk actieplan.",
        "facts": [("Duur", "90 min"), ("Metingen", "20+"), ("Investering", "€250")],
        "hero_alt": "Casper Boekee met Thai pads in de ring, in zwart-wit",
        "feat_eyebrow": "Het assessment",
        "feat_h": "Wat we testen",
        "tests": [
            ("Gezondheid & vitale waarden", "Je startpunt, voordat we iets belasten.", ["Rusthartslag", "Bloeddruk", "Lengte en lichaamsgewicht"]),
            ("Lichaamssamenstelling", "Gemeten met huidplooimeter en meetlint, niet geschat door een weegschaal.", ["Vetpercentage (huidplooimeting)", "Omtrekmaten: taille, heupen, borst, armen en bovenbenen", "Taille-heupverhouding"]),
            ("Houding", "Een statische houdinganalyse van vijf belangrijke gebieden.", ["Stand van het hoofd", "Schouders", "Bovenrug", "Bekkenstand", "Uitlijning van benen en voeten"]),
            ("Beweging & mobiliteit", "Hoe goed je beweegt, gemeten in graden met een goniometer.", ["Overhead squat assessment", "Schoudermobiliteit", "Heupmobiliteit", "Flexibiliteit hamstrings", "Enkelmobiliteit"]),
            ("Kracht & stabiliteit", "Getest op jouw niveau, links en rechts.", ["Knijpkracht met handdynamometer", "Balans op één been", "Core-stabiliteit", "Krachttests passend bij je niveau"]),
            ("Conditie", "Een cardiotest met live hartslagmeting (Polar H10).", ["Cardiotest met hartslagzones", "Hartslagherstel", "Geschatte VO2max"]),
        ],
        "get_eyebrow": "Wat je krijgt",
        "get_h": "Resultaten waar je iets mee kunt",
        "deliverables": [
            ("Persoonlijk rapport", "Al je resultaten in één helder rapport, vergeleken met normwaarden voor jouw leeftijd en geslacht."),
            ("Top 3 prioriteiten", "Wat nu het belangrijkst is voor jouw doel, en waarom."),
            ("Actieplan", "Concrete trainingsadviezen waar je direct mee aan de slag kunt."),
            ("Nabespreking", "20 tot 30 minuten om samen je rapport en de opties door te nemen."),
        ],
        "how_eyebrow": "Zo werkt het",
        "how_h": "Van intake tot actieplan",
        "steps": [
            ("Intakeformulier", "Je vult het intakeformulier in, zodat ik je doelen, achtergrond en eventuele blessures ken."),
            ("De scan", "75 tot 90 minuten bij Patrick's Gym, aangepast aan jouw niveau."),
            ("Je rapport", "Binnen 48 uur je persoonlijke rapport: resultaten, je top 3 prioriteiten en een actieplan."),
            ("Nabespreking", "Een gesprek van 20 tot 30 minuten waarin we je rapport en de opties doornemen."),
        ],
        "invest_eyebrow": "Investering",
        "invest_h": "€250",
        "invest_p": "Start je binnen 14 dagen met een 10-sessiepakket of coachingtraject, dan wordt de volledige €250 verrekend.",
        "cta": "Plan je scan",
        "cta_btn": "Stuur een bericht",
        "cta_p": "Stuur me een bericht via het contactformulier of WhatsApp om je scan te plannen.",
    },
    "contact_page": {
        "eyebrow": "Contact",
        "h1": "Neem contact op",
        "lead": "Vragen over Muay Thai, krachttraining of persoonlijke coaching? Stuur me een bericht, dan bespreken we je doel.",
    },
    "privacy": {
        "eyebrow": "Privacy",
        "h1": "Privacyverklaring",
        "updated": "Laatst bijgewerkt: 30 september 2026",
        "sections": [
            ("Wie ik ben", ["Casper Boekee Personal Training, Amsterdam. KvK-nummer 89761286. Voor vragen over je gegevens: info@casperboekee.com."]),
            ("Wat ik verzamel", ["Als je het contactformulier verstuurt, ontvang ik je naam, e-mailadres, telefoonnummer (als je dat invult), waar je interesse in hebt en je bericht.", "Deel in het formulier liever geen medische gegevens. Die bespreken we persoonlijk tijdens de intake."]),
            ("Waarom", ["Ik gebruik je gegevens alleen om op je aanvraag te reageren en je kennismaking of training te plannen. Ik gebruik ze niet voor nieuwsbrieven of advertenties."]),
            ("Hoe lang", ["Ik bewaar je aanvraag zolang dat nodig is om hem af te handelen. Word je geen klant, dan verwijder ik hem binnen 12 maanden."]),
            ("Wie verwerkt het nog meer", ["Het formulier wordt door Web3Forms bij mijn mailbox afgeleverd. Mijn e-mail staat bij Google. Deze website staat bij GitHub Pages, dat voor de beveiliging IP-adressen van bezoekers vastlegt, en laadt de lettertypes van Google Fonts.", "Deze website gebruikt geen statistieken of tracking-cookies."]),
            ("Jouw rechten", ["Je kunt me altijd vragen je gegevens in te zien, te corrigeren of te verwijderen via info@casperboekee.com. Je kunt ook een klacht indienen bij de Autoriteit Persoonsgegevens."]),
        ],
    },
    "notfound": {"h1": "Pagina niet gevonden", "p": "Deze pagina bestaat niet (meer).", "link": "Terug naar home"},
}

if SITE["goatcounter"]:
    EN["privacy"]["sections"][4][1][1] = "To see how the website is used, I count visits with GoatCounter. It uses no cookies and stores no personal data or full IP addresses, so you can't be identified."
    NL["privacy"]["sections"][4][1][1] = "Om te zien hoe de website gebruikt wordt, tel ik bezoeken met GoatCounter. Dat gebruikt geen cookies en bewaart geen persoonsgegevens of volledige IP-adressen, dus je bent niet herkenbaar."

LANGS = {"en": EN, "nl": NL}
